quora/quora/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [ 
	url(r'^admin/', admin.site.urls),

	url(r'^userprofile/',include('userprofile.urls'),),
	url(r'^account/',include('usersignup.urls', namespace = 'usersignup',)),

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

quora/userprofile/urls.py
from django.conf.urls import url
from .views import profile,home
# from .views import Temp

urlpatterns=[
	url(r'^profilecreate/$',profile,name='profilecreate'),
	url(r'^home/$',home,name='home'),
	# url(r'^temp/$',Temp.as_view(),)


]

quora/userprofile/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Profile(models.Model):
	MALE='M'
	FEMALE='F'
	CHOICES=((MALE,"MALE"),(FEMALE,"FEMALE"),)
	user = models.OneToOneField(User, on_delete=models.CASCADE) #one to one field enable one profile to one user
	country = models.CharField(max_length=20, blank=True, null =  True)
	city = models.CharField(max_length=20, blank=True, null =  True)
	street_name = models.CharField(max_length=20, blank=True, null =  True)
	street_number = models.CharField(max_length=20, blank=True, null =  True) # this is extra field to user model
	gender=models.CharField(max_length=10,choices=CHOICES,null=True,blank=True)
	bio = models.CharField(max_length= 500, blank=True, null=True)
	birth_date = models.DateField(blank=True, null=True)
	contact = models.IntegerField(blank=True, null=True)
	job=models.CharField(max_length= 100, blank=True, null=True)
	profile_picture=models.ImageField(blank=True,null=True,upload_to='Images_Quora/%Y-%m-%d')

	class Meta:
		db_table = 'auth_profile' #create customize dB table 


	def __str__(self):
		return self.user.username



@receiver(post_save, sender=User) #signal used to create a object related to user instance
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User) #signal used to save a object related to user instance
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

quora/userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class ProfileForm(forms.ModelForm):
        MALE='M'
        FEMALE='F'
        CHOICES=((MALE,"MALE"),(FEMALE,"FEMALE"),)

	first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', }),
        max_length=30,
        required=False)

	last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=False)

        gender=forms.ChoiceField(choices=CHOICES,required=True,)

	country = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

        city = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

        street_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False) 

        street_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

	bio = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=500,
        required=False)

	birth_date = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id':'datepicker'},
        	),max_length=50,required=False)

	contact = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

        city = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

        profile_picture=forms.ImageField(help_text="Upload image: ", required=False),

        job = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

	class Meta:
		model = Profile
		fields = ['first_name','last_name', 'profile_picture','contact','bio','job','gender','country','city','street_name','street_number']

quora/userprofile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import ProfileForm
from django.views.generic import TemplateView

def home(request):
	return HttpResponse("this is home")

@login_required
def profile(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.profile.gender= form.cleaned_data.get('gender')
            user.profile.country = form.cleaned_data.get('country')
            user.profile.city = form.cleaned_data.get('city')
            user.profile.street_name= form.cleaned_data.get('street_name')
            user.profile.street_number = form.cleaned_data.get('street_number')
            user.profile.bio = form.cleaned_data.get('bio')
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.profile.contact = form.cleaned_data.get('contact')
            user.profile.profile_picture= form.cleaned_data.get('profile_picture')
            user.profile.job= form.cleaned_data.get('job')
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile was successfully edited.')
            return redirect('/home/')

    else:
        form = ProfileForm(instance=user, initial={
            'first_name':user.first_name,
            'last_name':user.last_name,
        	'gender':user.profile.gender,
            'country':user.profile.country,
            'city':user.profile.city,
            'street_name':user.profile.street_name,
            'street_number':user.profile.street_number,
            'bio':user.profile.bio,
            'birth_date':user.profile.birth_date,
            'contact':user.profile.contact,
            'profile_picture':user.profile.profile_picture,
            'job':user.profile.job,
            
            })
    return render(request, 'userprofile/profile.html', {'form': form})
    # return render(request, 'createprofile.html', {'form': form})

# class Temp(TemplateView):
#     template_name='createprofile.html'

 

quora/userprofile/templates/userprofile/profile.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}" />
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
	<title>Paper Bootstrap Wizard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/paper-bootstrap-wizard.css' %}" rel="stylesheet" />

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link href="{% static 'css/demo.css' %}" rel="stylesheet" />

	<!-- Fonts and Icons -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
	<link href="{% static 'css/themify-icons.css' %}" rel="stylesheet">
</head>

<body>
	<div class="image-container set-full-height" style="background-image: url('{% static "img/paper-1.jpeg" %}' )">
	    <!--   Creative Tim Branding   -->


		<!--  Made With Paper Kit  -->
		<a href="http://demos.creative-tim.com/paper-kit?ref=paper-bootstrap-wizard" class="made-with-pk">
			<div class="brand">PK</div>
			<div class="made-with">Made with <strong>Paper Kit</strong></div>
		</a>

	     <!--   Big container   -->
	    <div class="container">
	        <div class="row">
		        <div class="col-sm-8 col-sm-offset-2">

		            <!--      Wizard container        -->
		            <div class="wizard-container">

		                <div class="card wizard-card" data-color="blue" id="wizardProfile">
		                    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
		                <!--        You can switch " data-color="orange" "  with one of the next bright colors: "blue", "green", "orange", "red", "azure"          -->

		                    	<div class="wizard-header text-center">
		                        	<h3 class="wizard-title">Create your profile</h3>
									<p class="category">Fill your personal information.</p>
		                    	</div>

								<div class="wizard-navigation">
									<div class="progress-with-circle">
									     <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="3" style="width: 21%;"></div>
									</div>
									<ul>
			                            <li>
											<a href="#about" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-user"></i>
												</div>
												Profile
											</a>
										</li>
			                            <li>
											<a href="#account" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-settings"></i>
												</div>
												About
											</a>
										</li>
			                            <li>
											<a href="#address" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-map"></i>
												</div>
												Address
											</a>
										</li>
			                        </ul>
								</div>
		                        <div class="tab-content">
		                            <div class="tab-pane" id="about">
		                            	<div class="row">
											<h5 class="info-text"> Please tell us more about yourself.</h5>
											<div class="col-sm-4 col-sm-offset-1">
												<div class="picture-container">
													<div class="picture">
														<img src="{% static 'img/default-avatar.jpg' %}" class="picture-src" id="wizardPicturePreview" title="" />
														<input id="id_profile_picture" name="profile_picture" type="file">
													</div>
													<h6>Choose Picture</h6>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<label>{{ form.first_name.label }} <small>(required)</small></label>
													<!-- <input name="firstname" type="text" class="form-control" placeholder="Andrew..."> -->
													{{ form.first_name }}
												</div>
												<div class="form-group">
													<label>{{ form.last_name.label}} <small>(required)</small></label>
													<!-- <input name="lastname" type="text" class="form-control" placeholder="Smith...">  -->
													{{ form.last_name }}
												</div>
											</div>
											<div class="col-sm-10 col-sm-offset-1">
													<label>{{ form.job.label }} <small>(required)</small></label>
													<!-- <input name="lastname" type="text" class="form-control" placeholder="Smith...">  -->
													{{ form.job }}
											</div>
										</div>
		                            </div>
		                            <div class="tab-pane" id="account">
		                                <h5 class="info-text"> What are you doing? (checkboxes) </h5>
		                                <div class="row">
		                                    <div class="col-sm-8 col-sm-offset-2">
		                                    	<div class="form-group">
													<label>{{form.bio.label}} <small>(required)</small></label>
													<!-- <input name="first_name" type="text" class="form-control" placeholder="Andrew..."> -->
													{{form.bio}}
													
												</div>
												<div class="form-group">
												 
													<label>{{form.gender.label}} </label>
													 <!-- name="gender" id="id_gen/der" class="form-control">
		                                                <option value="MALE"> MALE </option>
		                                                <option value="FEMALE"> FEMALE </option> -->
		                                                {{form.gender}}
													
												</div>
												
												<div class="form-group">
													<label>{{form.birth_date.label}} <small>(required)</small></label>
													<!-- <input name="first_name" type="text" class="form-control" placeholder="Andrew..."> -->
													{{form.birth_date}}
													
												</div>
												<div class="form-group">
													<label>{{ form.contact.label}} <small>(required)</small></label>
													<!-- <input name="lastname" type="text" class="form-control" placeholder="Smith..."> -->
													{{form.contact}}
												</div>
		                                        
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="tab-pane" id="address">
		                                <div class="row">
		                                    <div class="col-sm-12">
		                                        <h5 class="info-text"> Are you living in a nice area? </h5>
		                                    </div>
		                                    <div class="col-sm-7 col-sm-offset-1">
		                                    	<div class="form-group">
		                                            <label>{{ form.street_name.label }}</label>
		                                            {{ form.street_name }}
		                                        </div>
		                                    </div>
		                                    <div class="col-sm-3">
		                                       <div class="form-group">
		                                            <label>{{ form.street_number.label }}</label>
		                                            {{ form.street_number }}
		                                        </div>
		                                    </div>
		                                    <div class="col-sm-5 col-sm-offset-1">
		                                        <div class="form-group">
		                                            <label>{{ form.city.label }}</label>
		                                            {{ form.city }}
		                                        </div>
		                                    </div>
		                                    <div class="col-sm-5">
		                                        <div class="form-group">
		                                             <label>{{ form.country.label }}</label>
		                                            {{ form.country }}
		                                        </div>
		                                    </div>
		                                   
		                                </div>
		                                 <div class="now-submit">
		                              <center>  <button type="submit" class='btn btn-submit btn-fill btn-warning btn-wd'>submit</button>
		                              </center>
		                            </div>
		                            </div>
		                        </div>
		                        <div class="wizard-footer">
		                            <div class="pull-right">
		                                <input type='button' class='btn btn-next btn-fill btn-warning btn-wd' name='next' value='Next' />
		                              
		                            </div>

		                            <div class="pull-left">
		                                <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Previous' />
		                            </div>

		                            <div class="clearfix"></div>
		                        </div>

		                    </form>
		                </div>
		            </div> <!-- wizard container -->
		        </div>
	    	</div><!-- end row -->
		</div> <!--  big container -->



</body>

	<!--   Core JS Files   -->
	<script src="{% static 'js/jquery-2.2.4.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/jquery.bootstrap.wizard.js' %}" type="text/javascript"></script>

	<!--  Plugin for the Wizard -->
	<script src="{% static 'js/paper-bootstrap-wizard.js' %}" type="text/javascript"></script>

	<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
	<script src="{% static 'js/jquery.validate.min.js' %}" type="text/javascript"></script>

</html>

quora/userprofile/templates/userprofile/wiz.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="assets/img/favicon.png" />
	<title>Paper Bootstrap Wizard by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<!-- CSS Files -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
	<link href="assets/css/paper-bootstrap-wizard.css" rel="stylesheet" />

	<!-- CSS Just for demo purpose, don't include it in your project -->
	<link href="assets/css/demo.css" rel="stylesheet" />

	<!-- Fonts and Icons -->
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
	<link href="assets/css/themify-icons.css" rel="stylesheet">
</head>

<body>
	<div class="image-container set-full-height" style="background-image: url('assets/img/paper-1.jpeg')">
	    <!--   Creative Tim Branding   -->
	    <a href="http://creative-tim.com">
	         <div class="logo-container">
	            <div class="logo">
	                <img src="assets/img/new_logo.png">
	            </div>
	            <div class="brand">
	                Creative Tim
	            </div>
	        </div>
	    </a>

		<!--  Made With Paper Kit  -->
		<a href="http://demos.creative-tim.com/paper-kit?ref=paper-bootstrap-wizard" class="made-with-pk">
			<div class="brand">PK</div>
			<div class="made-with">Made with <strong>Paper Kit</strong></div>
		</a>

	    <!--   Big container   -->
	    <div class="container">
	        <div class="row">
		        <div class="col-sm-8 col-sm-offset-2">

		            <!--      Wizard container        -->
		            <div class="wizard-container">

		                <div class="card wizard-card" data-color="orange" id="wizardProfile">
		                    <form action="" method="">
		                <!--        You can switch " data-color="orange" "  with one of the next bright colors: "blue", "green", "orange", "red", "azure"          -->

		                    	<div class="wizard-header text-center">
		                        	<h3 class="wizard-title">Create your profile</h3>
									<p class="category">This information will let us know more about you.</p>
		                    	</div>

								<div class="wizard-navigation">
									<div class="progress-with-circle">
									     <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="3" style="width: 21%;"></div>
									</div>
									<ul>
			                            <li>
											<a href="#about" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-user"></i>
												</div>
												About
											</a>
										</li>
			                            <li>
											<a href="#account" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-settings"></i>
												</div>
												Work
											</a>
										</li>
			                            <li>
											<a href="#address" data-toggle="tab">
												<div class="icon-circle">
													<i class="ti-map"></i>
												</div>
												Address
											</a>
										</li>
			                        </ul>
								</div>
		                        <div class="tab-content">
		                            <div class="tab-pane" id="about">
		                            	<div class="row">
											<h5 class="info-text"> Please tell us more about yourself.</h5>
											<div class="col-sm-4 col-sm-offset-1">
												<div class="picture-container">
													<div class="picture">
														<img src="assets/img/default-avatar.jpg" class="picture-src" id="wizardPicturePreview" title="" />
														<input type="file" id="wizard-picture">
													</div>
													<h6>Choose Picture</h6>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<label>First Name <small>(required)</small></label>
													<input name="firstname" type="text" class="form-control" placeholder="Andrew...">
												</div>
												<div class="form-group">
													<label>Last Name <small>(required)</small></label>
													<input name="lastname" type="text" class="form-control" placeholder="Smith...">
												</div>
											</div>
											<div class="col-sm-10 col-sm-offset-1">
												<div class="form-group">
													<label>Email <small>(required)</small></label>
													<input name="email" type="email" class="form-control" placeholder="andrew@creative-tim.com">
												</div>
											</div>
										</div>
		                            </div>
		                            <div class="tab-pane" id="account">
		                                <h5 class="info-text"> What are you doing? (checkboxes) </h5>
		                                <div class="row">
		                                    <div class="col-sm-8 col-sm-offset-2">
		                                        <div class="col-sm-4">
		                                            <div class="choice" data-toggle="wizard-checkbox">
		                                                <input type="checkbox" name="jobb" value="Design">
		                                                <div class="card card-checkboxes card-hover-effect">
		                                                    <i class="ti-paint-roller"></i>
															<p>Design</p>
		                                                </div>
		                                            </div>
		                                        </div>
		                                        <div class="col-sm-4">
		                                            <div class="choice" data-toggle="wizard-checkbox">
		                                                <input type="checkbox" name="jobb" value="Code">
		                                                <div class="card card-checkboxes card-hover-effect">
		                                                    <i class="ti-pencil-alt"></i>
															<p>Code</p>
		                                                </div>
		                                            </div>
		                                        </div>
		                                        <div class="col-sm-4">
		                                            <div class="choice" data-toggle="wizard-checkbox">
		                                                <input type="checkbox" name="jobb" value="Develop">
		                                                <div class="card card-checkboxes card-hover-effect">
		                                                    <i class="ti-star"></i>
															<p>Develop</p>
		                                                </div>
		                                            </div>
		                                        </div>
		                                    </div>
		                                </div>
		                            </div>
		                            <div class="tab-pane" id="address">
		                                <div class="row">
		                                    <div class="col-sm-12">
		                                        <h5 class="info-text"> Are you living in a nice area? </h5>
		                                    </div>
		                                    <div class="col-sm-7 col-sm-offset-1">
		                                    	<div class="form-group">
		                                            <label>Street Name</label>
		                                            <input type="text" class="form-control" placeholder="5h Avenue">
		                                        </div>
		                                    </div>
		                                    <div class="col-sm-3">
		                                        <div class="form-group">
		                                            <label>Street Number</label>
		                                            <input type="text" class="form-control" placeholder="242">
		                                        </div>
		                                    </div>
		                                    <div class="col-sm-5 col-sm-offset-1">
		                                        <div class="form-group">
		                                            <label>City</label>
		                                            <input type="text" class="form-control" placeholder="New York...">
		                                        </div>
		                                    </div>
		                                    <div class="col-sm-5">
		                                        <div class="form-group">
		                                            <label>Country</label><br>
		                                            <select name="country" class="form-control">
		                                                <option value="Afghanistan"> Afghanistan </option>
		                                                <option value="Albania"> Albania </option>
		                                                <option value="Algeria"> Algeria </option>
		                                                <option value="American Samoa"> American Samoa </option>
		                                                <option value="Andorra"> Andorra </option>
		                                                <option value="Angola"> Angola </option>
		                                                <option value="Anguilla"> Anguilla </option>
		                                                <option value="Antarctica"> Antarctica </option>
		                                                <option value="...">...</option>
		                                            </select>
		                                        </div>
		                                    </div>
		                                </div>
		                            </div>
		                        </div>
		                        <div class="wizard-footer">
		                            <div class="pull-right">
		                                <input type='button' class='btn btn-next btn-fill btn-warning btn-wd' name='next' value='Next' />
		                                <input type='button' class='btn btn-finish btn-fill btn-warning btn-wd' name='finish' value='Finish' />
		                            </div>

		                            <div class="pull-left">
		                                <input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Previous' />
		                            </div>
		                            <div class="clearfix"></div>
		                        </div>
		                    </form>
		                </div>
		            </div> <!-- wizard container -->
		        </div>
	    	</div><!-- end row -->
		</div> <!--  big container -->

	    <div class="footer">
	        <div class="container text-center">
	            Made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com">Creative Tim</a>. Free download <a href="http://www.creative-tim.com/product/paper-bootstrap-wizard">here.</a>
	        </div>
	    </div>
	</div>

</body>

	<!--   Core JS Files   -->
	<script src="assets/js/jquery-2.2.4.min.js" type="text/javascript"></script>
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="assets/js/jquery.bootstrap.wizard.js" type="text/javascript"></script>

	<!--  Plugin for the Wizard -->
	<script src="assets/js/paper-bootstrap-wizard.js" type="text/javascript"></script>

	<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
	<script src="assets/js/jquery.validate.min.js" type="text/javascript"></script>

</html>